# Generated by Django 4.0.5 on 2022-06-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NaszeOsiedle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inhabitant',
            old_name='first_mane',
            new_name='first_name',
        ),
    ]
