# Generated by Django 4.0.5 on 2022-06-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaszeOsiedle', '0002_rename_first_mane_inhabitant_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
        migrations.AlterField(
            model_name='vote',
            name='end_date',
            field=models.DateTimeField(help_text='dd.mm.rrrr, --:--'),
        ),
    ]
